// How to drive this CRM, written for something that has never seen it.
//
// The reader is a browsing agent: it can read a page, click, type and follow a
// link, and it has no idea what is on the other side of any of them. What it
// lacks is not intelligence, it is the thing a person picks up in their first
// week -- that money lives under Payments and not on the Dashboard, that
// publishing an ad never spends anything, that the CRM cannot delete a Meta ad
// at all. Guessing those costs a wrong click or a wrong conclusion, and both
// are worse here than not acting.
//
// So this is deliberately not a feature list. It is written as answers to the
// questions something actually asks while it works:
//
//   - where does this piece of information live
//   - how do I change it
//   - how do I get it out
//   - what will not work no matter how many times I try
//
// One spec, three consumers -- same reasoning as ghlSetupFields.js:
//
//   1. /guide, for anything that runs JavaScript, and for people
//   2. public/llms.txt, generated by scripts/build-agent-guide.mjs, for
//      anything that does not -- the same argument as privacy.html, which is a
//      static file because Meta's reviewer does not reliably run JS
//   3. the Copy button on /guide, for pasting into a chat
//
// ROUTES are checked against the router and the nav by
// scripts/check-agent-guide.mjs. A page added, moved or renamed without this
// file being updated fails that check, which is the only reason to trust
// anything written below: a stale guide is worse than none, because it is
// followed confidently.

export const GUIDE_TITLE = 'Navigating this CRM'

export const GUIDE_INTRO = [
  'This is the internal CRM for a marketing agency that runs paid advertising for home-services businesses — HVAC, plumbing, electrical and similar trades. Each of those businesses is a "client". The agency runs their Meta (Facebook and Instagram) ads, their Google Local Services Ads, their Google Business Profile, and for some of them a GoHighLevel account that handles automated texts and calls.',
  'Everything is one screen deep. There is no login and no per-user permission: whoever opens the CRM sees all of it, and anything on screen can be changed by whoever is looking at it. Treat that as a reason for care rather than permission — a wrong edit here is a wrong number in a real client report.',
  'Numbers about ad performance are not live. A scheduled job copies yesterday from Meta each morning, so today is usually absent and the freshest figure is yesterday. Money is different: payments come from Stripe, and Stripe is treated as the truth whenever the CRM disagrees with it.',
]

// Every route in the app. `nav` is the sidebar label where there is one; a page
// reachable only by clicking through carries nav: null.
export const ROUTES = [
  {
    path: '/',
    aliases: ['/dashboard'],
    name: 'Dashboard',
    nav: 'Dashboard',
    purpose:
      'The operations hub, and the right place to start. Answers "where does every client stand and what needs doing today". Carries no billing figures at all by design — money is on Payments.',
    contains: [
      'Ad delivery alerts, at the very top, and only when something is wrong: a client whose ad account is disabled or unsettled, or whose ads have gone quiet. This is the most important thing on the page and it is invisible on a good day.',
      'Unread client form submissions, same rule — shown only when there are some.',
      'Three counts: Clients, Open work, KPIs logged (as "n of m" for this week).',
      '"Channels live" — how many clients have Meta ads, Google LSA, Google Business and GHL running. GHL is counted out of the clients who bought it, not out of everyone.',
      '"This week across all clients" — ad spend, leads and cost per lead, each with last week beside it.',
      '"What to do today" — grouped lists of late deliverables, missing KPIs and clients missing a channel, each naming the client. Replaced by "All caught up" when there is nothing.',
    ],
    actions: ['Nothing is edited here. Every item links to the client or page where it can be.'],
  },
  {
    path: '/clients',
    name: 'Clients',
    nav: 'Clients',
    purpose: 'The roster, and the way in to any single client.',
    contains: [
      'One row per client: name, business, industry, market, which channels are live, then this week\'s spend, leads and cost per lead, and their setup fee and monthly subscription.',
      'A row highlighted amber has KPIs that have not been logged this week.',
    ],
    actions: [
      'Search box, matching business, client, industry or market.',
      'Filter buttons: All, Meta live, Meta not yet, LSA optimized, LSA not yet, GBP optimized, GBP not yet, and two for GHL.',
      'A "New Client" button in the page header opens a form in a modal.',
      'Clicking any row opens that client\'s page.',
    ],
  },
  {
    path: '/client/:clientId',
    name: 'Client detail',
    nav: null,
    purpose:
      'Everything about one client, on a single long page. This is where most work actually happens. Reach it by clicking a client on /clients rather than by constructing the URL — clientId is a UUID and is not guessable from the name.',
    contains: [
      'Status switches: Meta ads, Google LSA, Google Business Profile, GHL build, and — only once GHL build is on — GHL account.',
      'Industry, Market, Meta budget per day, LSA budget per day.',
      '"Client forms" — whether the onboarding form and the GHL setup form have come back, and the links to send them.',
      'Tasks, with a progress bar.',
      'Weekly KPI History, Weekly Work Log, Creative Log.',
      'The Meta ad account connection: which ad account, Page and pixel this client advertises with.',
      'Ad performance, anchored at #ad-performance so it can be linked to directly.',
      'Ad Doctor — kill and scale verdicts from the playbook, run against the last 30 days of synced data, with the arithmetic shown. It never pauses anything on its own.',
      'Deliverables for this client, Client Files, and Payments & Billing.',
    ],
    actions: [
      '"Ad Studio" in the header opens the ad builder in a modal (see below).',
      '"Ask about <client>" opens a chat about this client that can read their data.',
      'Each status switch saves immediately on click. There is no separate save.',
      '"Archive client" is at the end of the switch row. Archiving excludes the client from MRR, the Meta sync and every list; it is reversible with "Restore client".',
      'Buttons open modals for logging weekly KPIs, adding a work log entry, and adding a creative entry.',
    ],
  },
  {
    path: '/deliverables',
    name: 'Deliverables',
    nav: 'Deliverables',
    purpose: 'The book of work across every client — what is promised and what is late.',
    contains: ['One row per deliverable, with its client, status and due date.'],
    actions: [
      'Status filters: open, todo, in progress, review, done, all.',
      'A client dropdown to narrow to one client.',
      '"New Deliverable" and, on any row, "Edit Deliverable".',
    ],
  },
  {
    path: '/payments',
    name: 'Payments & Revenue',
    nav: 'Payments',
    purpose:
      'All money. MRR, what has been collected, what is overdue, and every disagreement with Stripe.',
    contains: [
      'MRR, Collected all time, and Overdue.',
      '"Setup fee not paid" and "Not subscribed yet" — the two onboarding money gaps, naming the clients.',
      'Stripe reconciliation, which flags where Stripe charged a different amount to what the CRM expects. Stripe wins these: the fix is to correct the CRM.',
      'Stripe payment links and unmatched Stripe payments waiting to be assigned to a client.',
      '"Paid out to Ethan" — whether each collected payment has had its split paid on, which is a separate question from whether the client paid.',
      'The payment ledger itself.',
    ],
    actions: [
      'Filters: paid, overdue, upcoming, all. Views: By client or By date. A client dropdown.',
      'On a payment row: "Mark Payment Paid" and "Edit Payment".',
      'MRR counts a client only when they have a scheduled monthly payment, and never counts archived clients. A client with a monthly fee typed in but no schedule contributes nothing — that is the usual explanation for MRR looking low.',
    ],
  },
  {
    path: '/reports',
    name: 'Performance Reports',
    nav: 'Reports',
    purpose: 'Ad performance across every client, over time. The place to answer "how are we doing".',
    contains: [
      'Ad spend, leads and cost per lead for the range, each against the previous equivalent range.',
      'A daily chart, switchable between ad spend, leads and cost per lead.',
      'A channel breakdown, per-client performance, and the agency\'s own businesses kept separate from client work.',
      'Ad accounts the sync found that no client claims, sorted by spend.',
      'The monthly client report log: who was sent one, who was skipped and why.',
    ],
    actions: [
      'In the page header: "Sync Meta" pulls fresh data from Meta on demand rather than waiting for the morning job. It can take a while and is safe to run.',
      'Scope: Live ads or All ads. Range: 14, 30 or 90 days.',
    ],
  },
  {
    path: '/sops',
    name: 'SOPs',
    nav: 'SOPs',
    purpose: 'The agency\'s written procedures. Reference material, not client data.',
    contains: ['Saved procedures, pinned ones first, each with its steps and any attachments.'],
    actions: ['Search, "New SOP", "Edit SOP", copy an SOP\'s text, and pin or unpin it.'],
  },
  {
    path: '/ai-search',
    name: 'AI Search Visibility',
    nav: 'AI Search',
    purpose:
      'Asks whether an AI assistant names a business when someone asks who to call, and who it names instead. Works on any business, client or not, so it doubles as a sales tool.',
    contains: [
      'A scan form: website, business name, city or service area, trade, and optionally a client to attach it to.',
      'Past scans, and a comparison of any scan against an earlier one for the same business — which questions now name them that did not before.',
    ],
    actions: [
      '"Run the scan" asks 15 real buyer questions with live web search. It takes a couple of minutes and shows its progress; do not assume it has hung.',
      'A scan attached to a client becomes their baseline, so a later scan can be measured against it.',
    ],
  },
  {
    path: '/guide',
    name: 'This guide',
    nav: 'Guide',
    purpose: 'This page. Also available as plain text at /llms.txt, which needs no JavaScript.',
    contains: ['Everything in this document.'],
    actions: ['A button copies the whole guide as plain text.'],
  },
  {
    path: '/onboarding/:token',
    name: 'Client onboarding form',
    nav: null,
    purpose:
      'NOT part of the CRM. This is the form a client fills in, opened with a private token in the link, and it deliberately shows none of the agency navigation. Do not treat it as an admin page and do not fill it in on a client\'s behalf unless asked to.',
    contains: [
      'The onboarding questions about their business, and the GoHighLevel account setup questions.',
      'A ?form=intake or ?form=ghl query narrows it to one half.',
    ],
    actions: ['It saves as the client types. There is no submit-and-lose-everything step.'],
  },
]

// "I need X" -> where X actually is. The single most useful section, because
// the honest answer is often a page whose name does not contain the word.
export const LOOKUPS = [
  {
    need: 'How much a client pays, or whether they have paid',
    where: 'Payments, or the "Payments & Billing" section on the client\'s own page',
    how: 'The client page shows one client\'s setup fee, monthly payment and what is collected. /payments shows all of them at once and is the better place to compare.',
  },
  {
    need: 'What is owed to Ethan, or what the business actually made',
    where: 'Payments → Profit split',
    how: 'One lifetime running balance, cash basis — everything ever collected, minus everything ever spent, split by the agreed percent, minus everything ever sent. There is no month to pick and nothing closes off, so a late expense just moves the balance. Every line of the arithmetic is shown, and "What the balance is made of" lists the individual client payments behind the total. A partner who paid a cost out of their own pocket is owed it back on top of their share.',
  },
  {
    need: 'What the business paid out, and to whom',
    where: 'Payments → Expenses',
    how: 'One row per cost. Anything marked shared comes off the top before the split; anything not stays recorded but out of it. This is a management view, not payroll — no withholding or 1099s are modelled.',
  },
  {
    need: 'Total monthly revenue',
    where: 'Payments → the MRR card',
    how: 'Not on the Dashboard. The Dashboard carries no money at all.',
  },
  {
    need: 'Why MRR looks wrong',
    where: 'Payments → the Stripe reconciliation panel',
    how: 'It names each client where Stripe collected a different amount to the CRM\'s figure. Stripe is right; correct the CRM. Also check the client is not archived and does have a scheduled monthly payment.',
  },
  {
    need: 'Whether a client\'s ads are actually running',
    where: 'Dashboard → the alerts at the top, then the client page → Meta ad account',
    how: 'An alert appears when an ad account is disabled, unsettled over an unpaid balance, or has gone quiet for a couple of days. Silence on the Dashboard means the accounts were healthy as of the last check.',
  },
  {
    need: 'Whether a client actually granted the Meta access they said they did',
    where: 'Deliverables → "What did they actually grant?" → Check access',
    how: 'Reads the permission level back from Meta per client. Catches the two things invisible from inside the CRM: an asset shared at reporting level only, and access that was never granted or has been revoked. It also lists assets granted to us that no client is connected to yet.',
  },
  {
    need: 'Yesterday\'s spend, leads or cost per lead',
    where: 'Reports for all clients, or the client page → Ad performance for one',
    how: 'Today is normally missing — the sync copies yesterday each morning. "Sync Meta" on Reports fetches fresh numbers if you need them now.',
  },
  {
    need: 'Which ad to turn off',
    where: 'The client page → Ad Doctor',
    how: 'It prints the kill and scale verdicts with the arithmetic behind each. It will not act on its own, and pausing is done from the CRM while deleting is not possible here at all.',
  },
  {
    need: 'What is late, or what is owed to a client',
    where: 'Deliverables, filtered to open; or the Dashboard\'s "What to do today"',
    how: 'The Dashboard lists the late ones by name. Deliverables is where they get edited.',
  },
  {
    need: 'Whether a client has sent their details back',
    where: 'The client page → "Client forms"',
    how: 'Shows not started, in progress or done for both the onboarding form and the GHL setup form, and gives you the link to send.',
  },
  {
    need: 'A client\'s photos, logo or documents',
    where: 'The client page → "Client Files"',
    how: 'Uploaded files are listed there. Some clients also share a Google Drive folder, which appears in the same area.',
  },
  {
    need: 'Ads that have already been designed',
    where: 'The client page → Ad Studio → "Saved ads"',
    how: 'Every saved design, in each size it was made in.',
  },
  {
    need: 'Which Facebook Page or pixel a client advertises with',
    where: 'The client page → the Meta ad account section',
    how: 'Filled in automatically once an ad account is connected. Blank usually means no ad account is connected yet.',
  },
  {
    need: 'How the agency does something',
    where: 'SOPs',
    how: 'Search it. This is written procedure, not client data.',
  },
  {
    need: 'Whether an AI assistant recommends a business',
    where: 'AI Search',
    how: 'Past scans are listed; run a new one to compare against an old one.',
  },
]

export const DOWNLOADS = [
  {
    what: 'One client file',
    how: 'Client page → Client Files → "Download" on the row. The button says "Saving..." while it works.',
  },
  {
    what: 'Every client file at once',
    how: 'Client page → Client Files → "Download All (n)". It builds a single zip in the browser, so it takes a moment and shows progress. One archive rather than a burst of downloads, because phones and Safari block those.',
  },
  {
    what: 'A finished ad image',
    how: 'Client page → Ad Studio → Design tab → the download button under an artboard. One PNG per size.',
  },
  {
    what: 'A previously saved ad',
    how: 'Client page → Ad Studio → "Saved ads" → "Download" for the size you want, or "Copy URL" for a link to it.',
  },
  {
    what: 'The GHL setup details as text',
    how: 'Client page → Client forms → the GHL setup form → "Copy Setup Brief". Written to be pasted to whoever or whatever is doing the setup, and it names any missing field rather than dropping it silently.',
  },
  {
    what: 'The message to send a client',
    how: 'Client page → Client forms → "Copy message". This is the whole email or text, form link included, not just the URL.',
  },
  {
    what: 'Anything else',
    how: 'There is no CSV or spreadsheet export anywhere in the CRM, and no PDF export. Do not go looking for one. Read the numbers off the page, or ask for an export to be built.',
  },
]

// The things that cost a wrong click, a wrong conclusion, or twenty minutes of
// retrying. Every one of these has actually caught somebody out.
export const GOTCHAS = [
  {
    title: 'Publishing an ad never spends money',
    body: 'Everything the CRM creates in Meta — campaigns, ad sets, ads — is created paused. Nothing delivers until somebody switches it on in Meta Ads Manager, which is a separate deliberate act outside this CRM. So publishing is safe; switching on is not.',
  },
  {
    title: 'The CRM cannot delete anything in Meta',
    body: 'It can create, and it can pause one live ad. It cannot delete a campaign, an ad set or an ad. Deleting is done in Ads Manager by hand, on purpose.',
  },
  {
    title: 'A broken ad set cannot be repaired',
    body: 'Meta fixes what an ad set promotes when the ad set is created and refuses to change it afterwards. If the CRM says an ad set cannot take ads, the answer is a new ad set — not a retry. It will hand you the budget and targeting to rebuild with.',
  },
  {
    title: 'Meta rate-limits per ad account, per hour',
    body: '"Too many API calls" is the ad account\'s quota, not a rejected ad. Nothing was created, there is nothing to clean up, and the quota refills on its own. Publishing five ads at once is the most demanding thing the CRM does; two smaller batches get through where one large one will not.',
  },
  {
    title: 'Ad numbers are yesterday\'s',
    body: 'A scheduled job copies Meta data each morning. Today is normally blank, and that is not a fault. "Sync Meta" on Reports fetches fresh figures on demand.',
  },
  {
    title: 'Stripe overrules the CRM',
    body: 'Where a fee in the CRM and a charge in Stripe disagree, Stripe is the real one because it is what the client was actually charged. Fix the CRM, not Stripe.',
  },
  {
    title: 'Archived clients vanish from everything',
    body: 'Archiving removes a client from MRR, the Meta sync and every list. A client who has "disappeared" is usually archived rather than deleted, and restoring is one click on their page.',
  },
  {
    title: 'There is no login',
    body: 'No sign-in, no accounts, no roles. Nothing on screen is protected by permission, so nothing prevents a wrong edit. The one exception is the client onboarding form, which is reached with a private token in its link.',
  },
  {
    title: 'GHL is not sold to everyone',
    body: 'Only some clients buy the GoHighLevel build, so a blank GHL section is normal rather than incomplete. Its coverage on the Dashboard is counted out of the clients on the plan, not out of every client.',
  },
  {
    title: 'The AI Search scan is slow on purpose',
    body: 'It asks 15 questions with live web search and takes a couple of minutes. It shows its progress. Do not reload the page or start it again.',
  },
]

/**
 * The whole guide as plain text.
 *
 * Written for two readers that both do badly with markup: a build step that
 * writes public/llms.txt, and a clipboard paste into a chat. Underlined
 * headings and "- " bullets survive both, where HTML and markdown tables do
 * not.
 */
export function formatAgentGuide({ baseUrl = '' } = {}) {
  const out = []
  const rule = (text, char) => text + '\n' + char.repeat(text.length)

  out.push(rule(GUIDE_TITLE.toUpperCase(), '='), '')
  for (const para of GUIDE_INTRO) out.push(para, '')

  out.push(rule('PAGES', '='), '')
  for (const route of ROUTES) {
    const paths = [route.path, ...(route.aliases || [])]
      .map((p) => (baseUrl ? baseUrl.replace(/\/$/, '') + p : p))
      .join('  or  ')
    out.push(rule(`${route.name}   ${paths}`, '-'))
    if (route.nav) out.push(`Sidebar: ${route.nav}`)
    out.push(route.purpose, '')
    out.push('What is on it:')
    for (const item of route.contains) out.push(`  - ${item}`)
    out.push('')
    out.push('What you can do:')
    for (const item of route.actions) out.push(`  - ${item}`)
    out.push('')
  }

  out.push(rule('WHERE TO FIND A PARTICULAR THING', '='), '')
  for (const l of LOOKUPS) {
    out.push(`${l.need}`)
    out.push(`  Go to: ${l.where}`)
    out.push(`  ${l.how}`, '')
  }

  out.push(rule('GETTING THINGS OUT', '='), '')
  for (const d of DOWNLOADS) {
    out.push(`${d.what}`)
    out.push(`  ${d.how}`, '')
  }

  out.push(rule('THINGS THAT WILL CATCH YOU OUT', '='), '')
  for (const g of GOTCHAS) {
    out.push(`${g.title}`)
    out.push(`  ${g.body}`, '')
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'
}
