import { supabase } from './supabaseClient'

// Marking a pipeline step done, from the board or the client page.
//
// The pipeline is computed from data, so "done" has to become a fact the
// computation reads. Where the fact has a home already (a live toggle, the
// link's submitted stamp, the call sheet) it is written there, so every other
// screen and the nightly jobs see it too. Where it has no home (photos that
// arrived by text, ads built outside the Studio) it becomes a step_overrides
// row: done, by whom, when, and undoable.

const FLAG_STEPS = {
  'ghl-live': { ghl_active: true },
  'go-live': { meta_ads_active: true },
  'gbp-access': { gbp_optimized: true },
  'lsa-access': { lsa_active: true },
}

const FLAG_UNDO = {
  'ghl-live': { ghl_active: false },
  'go-live': { meta_ads_active: false },
  'gbp-access': { gbp_optimized: false },
  'lsa-access': { lsa_active: false },
}

/** Steps a person is not allowed to wave through: money is recorded on Payments. */
export const NOT_MARKABLE = new Set(['setup-fee'])

async function latestLink(clientId) {
  const { data } = await supabase
    .from('onboarding_links')
    .select('id')
    .eq('client_id', clientId)
    .eq('revoked', false)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle()
  return data?.id || null
}

async function stampLink(clientId, field) {
  const id = await latestLink(clientId)
  const stamp = new Date().toISOString()
  if (id) {
    const { error } = await supabase.from('onboarding_links').update({ [field]: stamp }).eq('id', id)
    if (error) throw error
    return
  }
  // No link was ever sent (the form was filled on the call). One row so the
  // stamp has somewhere to live; the token is generated by the table.
  const { error } = await supabase.from('onboarding_links').insert({ client_id: clientId, [field]: stamp })
  if (error) throw error
}

async function override(clientId, stepKey, by, note) {
  const { error } = await supabase
    .from('step_overrides')
    .upsert({ client_id: clientId, step_key: stepKey, done_at: new Date().toISOString(), done_by: by || null, note: note || null }, { onConflict: 'client_id,step_key' })
  if (error) throw error
}

/**
 * Mark one step done for a client. `by` is the teammate's name, kept on the
 * override so the row can say who. Throws with a plain reason when the step
 * cannot be marked by hand.
 */
export async function markStepDone(client, step, { by = '', note = '' } = {}) {
  const key = step?.key
  if (!key) throw new Error('No step.')
  if (NOT_MARKABLE.has(key)) throw new Error('The setup fee is recorded on the Payments page, not marked here.')

  if (FLAG_STEPS[key]) {
    const { error } = await supabase.from('clients').update(FLAG_STEPS[key]).eq('id', client.id)
    if (error) throw error
    return { how: 'flag' }
  }
  if (key === 'onboarding-form') {
    await stampLink(client.id, 'intake_submitted_at')
    return { how: 'link' }
  }
  if (key === 'ghl-form') {
    await stampLink(client.id, 'ghl_submitted_at')
    return { how: 'link' }
  }
  if (key === 'onboarding-call') {
    const { error } = await supabase
      .from('onboarding_call_steps')
      .upsert({ client_id: client.id, step_key: 'marked-done', done_at: new Date().toISOString() }, { onConflict: 'client_id,step_key' })
    if (error) throw error
    return { how: 'call' }
  }
  await override(client.id, key, by, note)
  return { how: 'override' }
}

/**
 * Take a mark back. A flag step flips its toggle off; an override row is
 * deleted; the link stamps and the call sheet are left alone, because those
 * record that something happened and the client page is where to change
 * them.
 */
export async function undoStepDone(client, step) {
  const key = step?.key
  if (FLAG_UNDO[key]) {
    const { error } = await supabase.from('clients').update(FLAG_UNDO[key]).eq('id', client.id)
    if (error) throw error
    return { how: 'flag' }
  }
  const { error } = await supabase.from('step_overrides').delete().eq('client_id', client.id).eq('step_key', key)
  if (error) throw error
  return { how: 'override' }
}

/**
 * Who is marking things done. Asked once per browser and kept, so a row can
 * say "Marked done by Maria" without a login.
 */
export function whoAmI() {
  let name = ''
  try {
    name = localStorage.getItem('crm.me') || ''
    if (!name) {
      name = (prompt('Your name, shown on what you mark done:') || '').trim()
      if (name) localStorage.setItem('crm.me', name)
    }
  } catch {
    // Storage blocked: the mark still lands, just without a name.
  }
  return name
}

/** Whether a done step can be undone from the board. */
export function canUndo(step) {
  return Boolean(step?.done) && (Boolean(step.manual) || Boolean(FLAG_UNDO[step.key]))
}
