-- ---------------------------------------------------------------------------
-- REMOVE THE HAND-BUILT PAYMENT SCHEDULE
--
-- Leaves only payments that came from Stripe: rows the webhook recorded
-- (stripe_event_id) or the CSV importer created (stripe_charge_id). Everything
-- else is the 12-month schedule generated by Billing Setup, which was a
-- stand-in until real payment data existed.
--
-- READ BEFORE RUNNING — two things stop working afterwards:
--
--   1. Nothing can be overdue. "Overdue" means a scheduled row whose date has
--      passed, and there will be no scheduled rows. The Overdue tile goes to
--      zero permanently.
--
--   2. invoice.payment_failed has nothing to mark. The webhook flags the oldest
--      outstanding scheduled row when a card is declined; with no schedule it
--      processes the event and changes nothing. This already happened once, to
--      Belk Heating and Cooling, because they had no schedule.
--
-- Both are fine if Stripe's own dunning is where failed payments get chased.
-- If not, the webhook should insert a flagged row instead of needing one to
-- exist, which is a change to supabase/functions/stripe-webhook.
--
-- Also worth knowing: Billing Setup on a client page will happily rebuild a
-- schedule, so the rows can come back by accident.
-- ---------------------------------------------------------------------------

-- 1. See what goes, before anything goes.
select c.name,
       count(*) as rows_to_delete,
       sum(p.amount) as total_value,
       count(*) filter (where p.status = 'paid') as marked_paid
from payments p
join clients c on c.id = p.client_id
where p.stripe_charge_id is null
  and p.stripe_event_id is null
group by c.name
order by c.name;

-- 2. Keep a copy. The container this was written in is temporary; a table is not.
drop table if exists payments_backup_before_stripe_only;
create table payments_backup_before_stripe_only as
select * from payments;

-- 3. Delete.
delete from payments
where stripe_charge_id is null
  and stripe_event_id is null;

-- 4. Confirm what is left is all from Stripe.
select count(*) as remaining,
       count(*) filter (where stripe_charge_id is not null) as from_import,
       count(*) filter (where stripe_event_id is not null) as from_webhook
from payments;

-- To undo:
--   insert into payments select * from payments_backup_before_stripe_only
--   on conflict (id) do nothing;
