-- Run this once in the Supabase SQL Editor.
--
-- Payment schedules used to be generated by a database trigger the moment a
-- client's status flipped to 'active'. That was wrong: clients start paying
-- before onboarding is finished, and the trigger always used a fixed 12 months
-- starting today with no way to set the amounts.
--
-- Billing is now entered in the app (client page -> Billing Setup), so the
-- trigger has to go or it will create a second, duplicate schedule the first
-- time a client is switched to active.

drop trigger if exists on_client_activate on clients;
drop function if exists create_payment_schedule();
