// The weekly client report: the week maths, who gets one, the numbers, the
// plain-English sentences, and the email and web copy. Plain JavaScript in a
// .ts file so the Edge Function (Deno) and the app (Vite) load the very same
// code; src/lib/weeklyReport.js re-exports it from supabase/functions/weekly-report/weekly.ts.
//
// WHAT THE REPORT IS FOR. A home-services owner wants to know three things
// on a Monday morning: what did I spend, what did I get, and is it working.
// So the report is five numbers, two or three sentences on what they mean,
// a short glossary, and one argument made every week: the number that
// decides whether the ads are worth it is the return on the leads, not the
// cost per lead, and the only person who knows that number is the owner.
// The web copy asks for it in one line.
//
// TONE. Short sentences, everyday words, no hype. Every sentence is a fixed
// template with the week's numbers dropped in; nothing here is generated by
// a model, so it reads the same way every week and never over-promises.

export const LIVE_STATUSES = ['ACTIVE', 'WITH_ISSUES']

const pad = (n) => String(n).padStart(2, '0')
export const isoDay = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
const fromIso = (s) => {
  const [y, m, d] = String(s).split('-').map(Number)
  return new Date(y, m - 1, d)
}
const addDays = (s, n) => {
  const d = fromIso(s)
  d.setDate(d.getDate() + n)
  return isoDay(d)
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const shortDate = (s) => {
  const d = fromIso(s)
  return `${MONTHS[d.getMonth()]} ${d.getDate()}`
}

/**
 * The Monday-to-Sunday week that ended before `today`. On a Monday that is
 * last week; on any other day it is the most recent complete week.
 */
export function reportWeek(today = new Date()) {
  const t = typeof today === 'string' ? fromIso(today) : new Date(today)
  // Days back to the most recent Sunday strictly before today.
  const dow = t.getDay() // 0 = Sunday
  const back = dow === 0 ? 7 : dow
  const sunday = new Date(t.getFullYear(), t.getMonth(), t.getDate() - back)
  const monday = new Date(sunday.getFullYear(), sunday.getMonth(), sunday.getDate() - 6)
  const from = isoDay(monday)
  const to = isoDay(sunday)
  return { from, to, key: from, label: weekLabel(from, to) }
}

/** A week from its Monday, for re-running a specific one. */
export function weekFrom(mondayIso) {
  const from = String(mondayIso)
  const to = addDays(from, 6)
  return { from, to, key: from, label: weekLabel(from, to) }
}

export function previousWeek(week) {
  return weekFrom(addDays(week.from, -7))
}

/** "Sep 29 to Oct 5" with the year when the week crosses into a new one. */
export function weekLabel(from, to) {
  const a = fromIso(from)
  const b = fromIso(to)
  const year = a.getFullYear() !== b.getFullYear() ? `, ${b.getFullYear()}` : ''
  return `${shortDate(from)} to ${shortDate(to)}${year}`
}

// Deliberately strict: a malformed address does not bounce cleanly.
export function validEmail(value) {
  const v = String(value || '').trim()
  return /^[^\s@]+@[^\s@]+\.[A-Za-z]{2,}$/.test(v)
}

const num = (v) => Number(v || 0) || 0
const r2 = (n) => Math.round(n * 100) / 100

/** Meta rows (ad_daily) and Google rows (google_campaign_daily) summed to one shape. */
export function sumMeta(rows = []) {
  const t = { spend: 0, leads: 0, impressions: 0, clicks: 0 }
  for (const r of rows) {
    t.spend += num(r.spend)
    t.leads += num(r.leads)
    t.impressions += num(r.impressions)
    t.clicks += num(r.clicks)
  }
  return t
}
export function sumGoogle(rows = []) {
  const t = { spend: 0, leads: 0, impressions: 0, clicks: 0 }
  for (const r of rows) {
    t.spend += num(r.cost)
    t.leads += num(r.conversions)
    t.impressions += num(r.impressions)
    t.clicks += num(r.clicks)
  }
  return t
}

/** Spend, leads, impressions, clicks, and the two rates. */
export function metrics(t) {
  const spend = r2(t.spend)
  const leads = Math.round(num(t.leads) * 10) / 10
  const impressions = Math.round(num(t.impressions))
  const clicks = Math.round(num(t.clicks))
  return {
    spend,
    leads,
    impressions,
    clicks,
    cpl: leads > 0 ? r2(spend / leads) : 0,
    ctr: impressions > 0 ? r2((clicks / impressions) * 100) : 0,
  }
}

const addTotals = (a, b) => ({
  spend: a.spend + b.spend,
  leads: a.leads + b.leads,
  impressions: a.impressions + b.impressions,
  clicks: a.clicks + b.clicks,
})

/**
 * Who gets a report. Every refusal carries a reason for the send log.
 * The address is the client's report email when set, else the contact
 * email on the intake form.
 */
export function eligibility({ client, intake, metaRows = [], googleRows = [] }) {
  if (!client) return { ok: false, reason: 'no client' }
  if (client.archived) return { ok: false, reason: 'archived' }
  if (client.is_internal) return { ok: false, reason: 'internal business, not a client' }
  if (client.weekly_report_enabled === false) return { ok: false, reason: 'weekly report switched off for this client' }
  const spend = sumMeta(metaRows).spend + sumGoogle(googleRows).spend
  if (spend <= 0) return { ok: false, reason: 'no ad spend last week' }
  const email = String(client.report_email || intake?.contact_email || '').trim()
  if (!email) return { ok: false, reason: 'no email on file (set one on the client, or on the onboarding form)' }
  if (!validEmail(email)) return { ok: false, reason: `email is not valid: ${email}` }
  return { ok: true, email }
}

/** Percent change, null when there is nothing to compare against. */
export function pctChange(now, before) {
  if (!before) return null
  return Math.round(((now - before) / before) * 100)
}

const stripWc = (name) => {
  // "WC_Summer | 2026-10-08 | AC died? Same-day" shows as "AC died? Same-day".
  const s = String(name || '').replace(/^wc_/i, '')
  const parts = s.split('|').map((x) => x.trim()).filter(Boolean)
  return parts.length > 1 ? parts[parts.length - 1] : s
}

/**
 * Everything the email and the web copy need, worked out once.
 *   lastAnswer: { jobs_booked, revenue, week } from the previous report, if the
 *   client answered it.
 */
export function buildWeeklyModel({ client, intake, week, metaRows = [], googleRows = [], prevMetaRows = [], prevGoogleRows = [], lastAnswer = null }) {
  const meta = sumMeta(metaRows)
  const google = sumGoogle(googleRows)
  const prevMeta = sumMeta(prevMetaRows)
  const prevGoogle = sumGoogle(prevGoogleRows)
  const totals = metrics(addTotals(meta, google))
  const previous = metrics(addTotals(prevMeta, prevGoogle))
  const hadPrevious = previous.spend > 0

  // The ad that brought the most leads, by name, across both channels.
  const byAd = new Map()
  for (const r of metaRows) {
    const key = r.ad_id || r.ad_name
    const a = byAd.get(key) || { name: stripWc(r.ad_name) || 'Untitled ad', leads: 0, spend: 0, channel: 'Meta' }
    a.leads += num(r.leads)
    a.spend += num(r.spend)
    byAd.set(key, a)
  }
  for (const r of googleRows) {
    const key = `g:${r.campaign_id || r.campaign_name}`
    const a = byAd.get(key) || { name: stripWc(r.campaign_name) || 'Google campaign', leads: 0, spend: 0, channel: 'Google' }
    a.leads += num(r.conversions)
    a.spend += num(r.cost)
    byAd.set(key, a)
  }
  const topAd = [...byAd.values()].filter((a) => a.leads > 0).sort((x, y) => y.leads - x.leads || x.spend - y.spend)[0] || null

  const avgJob = num(intake?.average_job_value) > 0 ? num(intake.average_job_value) : null

  const model = {
    client: { name: client.name },
    week,
    channels: {
      meta: meta.spend > 0 ? metrics(meta) : null,
      google: google.spend > 0 ? metrics(google) : null,
    },
    totals,
    previous: hadPrevious ? previous : null,
    deltas: hadPrevious
      ? {
          spend: pctChange(totals.spend, previous.spend),
          leads: pctChange(totals.leads, previous.leads),
          cpl: pctChange(totals.cpl, previous.cpl),
          ctr: pctChange(totals.ctr, previous.ctr),
          impressions: pctChange(totals.impressions, previous.impressions),
        }
      : null,
    topAd: topAd ? { name: topAd.name, leads: Math.round(topAd.leads * 10) / 10, spend: r2(topAd.spend), channel: topAd.channel } : null,
    avgJob,
    lastAnswer: lastAnswer && (num(lastAnswer.jobs_booked) > 0 || num(lastAnswer.revenue) > 0) ? { jobs: num(lastAnswer.jobs_booked), revenue: num(lastAnswer.revenue), week: lastAnswer.week || '', spend: num(lastAnswer.spend) } : null,
  }
  model.summary = summarySentences(model)
  model.returnNote = returnNote(model)
  return model
}

export const money = (n) => {
  const v = Number(n || 0)
  const whole = Math.abs(v) >= 100 || Number.isInteger(v)
  return `$${v.toLocaleString('en-US', { minimumFractionDigits: whole ? 0 : 2, maximumFractionDigits: whole ? 0 : 2 })}`
}
const plural = (n, one, many) => (Number(n) === 1 ? one : many)
const leadsWord = (n) => `${n} ${plural(n, 'lead', 'leads')}`

/**
 * Two or three sentences on what the week's numbers mean. Fixed templates,
 * the week's numbers dropped in. Each case is one plain thought.
 */
export function summarySentences(model) {
  const { totals, previous, deltas } = model
  const out = []

  if (totals.leads === 0) {
    out.push(`No leads came in last week on ${money(totals.spend)} of ad spend.`)
    if (totals.impressions > 0 && totals.ctr < 1) {
      out.push('The ads were shown but few people tapped, which usually means the same people have seen them too many times. A fresh ad is the fix, and that is what we work on first.')
    } else {
      out.push('A week with no leads is one we look into straight away, so expect to hear from us before the next report.')
    }
    return out
  }

  if (!previous) {
    out.push(`You got ${leadsWord(totals.leads)} last week from ${money(totals.spend)} in ads, which works out to ${money(totals.cpl)} per lead.`)
    out.push('This is your first full week, so there is nothing to compare it with yet. Next week you will see whether each number went up or down.')
  } else {
    const dl = totals.leads - previous.leads
    const leadsBit =
      dl > 0 ? `up from ${previous.leads} the week before` : dl < 0 ? `down from ${previous.leads} the week before` : `the same as the week before`
    out.push(`You got ${leadsWord(totals.leads)} last week from ${money(totals.spend)} in ads, ${leadsBit}.`)
    if (totals.cpl > 0 && previous.cpl > 0) {
      const dc = totals.cpl - previous.cpl
      if (Math.abs(dc) < 1) out.push(`Each lead cost about ${money(totals.cpl)}, about the same as the week before.`)
      else if (dc < 0) out.push(`Each lead cost ${money(totals.cpl)}, ${money(Math.abs(dc))} less than the week before.`)
      else out.push(`Each lead cost ${money(totals.cpl)}, ${money(dc)} more than the week before. Cost per lead moves around week to week; the trend over a month is what we watch.`)
    } else if (totals.cpl > 0) {
      out.push(`Each lead cost ${money(totals.cpl)}.`)
    }
  }

  if (totals.impressions > 0) {
    if (totals.ctr >= 2) out.push(`${totals.ctr}% of the people who saw the ad tapped it, which is a strong sign the ad is catching attention.`)
    else if (totals.ctr < 0.8) out.push(`${totals.ctr}% of the people who saw the ad tapped it, which is on the low side. That usually means the ad needs refreshing, and new creative is part of every month.`)
  }

  return out.slice(0, 3)
}

/**
 * The argument the report makes every week: judge the ads on what the leads
 * turned into, not on what they cost. Worked with the client's own numbers
 * when we have them.
 */
export function returnNote(model) {
  const { totals, avgJob, lastAnswer } = model
  const lines = []
  if (lastAnswer && lastAnswer.revenue > 0 && lastAnswer.spend > 0) {
    const back = Math.round((lastAnswer.revenue / lastAnswer.spend) * 100) / 100
    lines.push(
      `Last week you told us the leads became ${lastAnswer.jobs} ${plural(lastAnswer.jobs, 'job', 'jobs')} worth ${money(lastAnswer.revenue)}. Against ${money(lastAnswer.spend)} in ads, that is ${money(back)} back for every $1 spent. That is the number that matters, and it is why we ask every week.`
    )
  } else if (lastAnswer && lastAnswer.jobs > 0) {
    lines.push(`Last week you told us the leads became ${lastAnswer.jobs} ${plural(lastAnswer.jobs, 'job', 'jobs')}. Add the dollar amount next time and we will show your return on the ads.`)
  }
  if (totals.leads > 0) {
    const jobs = Math.max(1, Math.round(totals.leads / 5))
    if (avgJob) {
      lines.push(
        `For this week: if ${jobs} of the ${totals.leads} leads ${plural(jobs, 'becomes', 'become')} a job at your usual ${money(avgJob)}, that is ${money(jobs * avgJob)} of work from ${money(totals.spend)} in ads.`
      )
    } else {
      lines.push(
        `For this week: if ${jobs} of the ${totals.leads} leads ${plural(jobs, 'becomes', 'become')} a job, what is that worth to you? Compare it with the ${money(totals.spend)} the ads cost. That comparison, not cost per lead, is how to judge the ads.`
      )
    }
  }
  return lines
}

/** What each number means, in the words a busy owner reads once. */
export const GLOSSARY = [
  { key: 'impressions', label: 'Impressions', text: 'How many times your ad was shown. Showings, not people: one person can see it three times.' },
  { key: 'ctr', label: 'Click-through rate', text: 'Out of every 100 people who saw the ad, how many tapped it. Around 1 is normal. 2 or more is good.' },
  { key: 'leads', label: 'Leads', text: 'People who sent their details, called, or filled in a form. These are the ones to call back fast. Speed decides who books.' },
  { key: 'cpl', label: 'Cost per lead', text: 'Ad spend divided by leads. Useful, but only half the story. A $90 lead that becomes a $9,000 install beats a $30 lead that never books.' },
]

export const WHY_RETURN = [
  'Cheap leads are not the goal. Booked jobs are.',
  'Cost per lead tells us the ads are working. It cannot tell us the leads were worth having. Only you know that, because you know which ones booked and what they paid.',
  'So every week we ask one question: how many of these leads turned into jobs, and roughly what were they worth? Tell us and the next report shows your return on the ads, which is the only number that decides whether to spend more or less.',
]

// ----------------------------------------------------------------- email
const INK = '#0F172A'
const MUTED = '#64748B'
const LINE = '#E2E8F0'
const SOFT = '#F8FAFC'
const BRAND = '#EA580C'

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

// Green when the move is good, red when it is bad, grey when it is neither
// (spend going up is just a fact, not a win or a loss).
function deltaHtml(value, { lowerIsBetter = false, neutral = false } = {}) {
  if (value == null || !Number.isFinite(value)) return ''
  const flat = Math.abs(value) < 1
  const up = value > 0
  const good = flat || neutral ? null : lowerIsBetter ? !up : up
  const colour = good === null ? MUTED : good ? '#15803D' : '#B91C1C'
  const arrow = flat ? '' : up ? '&#9650;' : '&#9660;'
  const words = flat ? 'same as last week' : `${arrow} ${Math.abs(value)}% vs last week`
  return `<div style="font-size:11px;color:${colour};padding-top:3px;">${words}</div>`
}

function tile(label, value, delta) {
  return (
    `<td width="20%" valign="top" style="padding:12px 8px;border:1px solid ${LINE};border-radius:8px;background:#fff;">` +
    `<div style="font-size:11px;color:${MUTED};text-transform:uppercase;letter-spacing:.3px;">${label}</div>` +
    `<div style="font-size:21px;font-weight:700;color:${INK};padding-top:3px;white-space:nowrap;">${value}</div>` +
    `${delta}</td>`
  )
}

const fmtInt = (n) => Number(n || 0).toLocaleString('en-US')
const fmtLeads = (n) => (Number.isInteger(Number(n)) ? String(n) : Number(n).toFixed(1))

export function renderWeeklySubject(model) {
  const { totals, week } = model
  if (totals.leads === 0) return `Your ads last week (${week.label}): ${money(totals.spend)} spent, no leads yet`
  return `Your ads last week (${week.label}): ${leadsWord(fmtLeads(totals.leads))} from ${money(totals.spend)}`
}

/**
 * The email. Tables and inline styles only, so it survives Gmail, Outlook
 * and the Mail app on a phone.
 */
export function renderWeeklyHtml(model, { agencyName = 'The Working Class Marketing', reportUrl = '' } = {}) {
  const { client, week, totals, deltas, channels, topAd, summary, returnNote: rn } = model
  const d = deltas || {}
  const first = client.name

  const channelLine =
    channels.meta && channels.google
      ? `<div style="font-size:12px;color:${MUTED};padding-top:10px;">Meta: ${fmtLeads(channels.meta.leads)} ${plural(channels.meta.leads, 'lead', 'leads')} from ${money(channels.meta.spend)}. Google: ${fmtLeads(channels.google.leads)} ${plural(channels.google.leads, 'lead', 'leads')} from ${money(channels.google.spend)}.</div>`
      : channels.meta
        ? `<div style="font-size:12px;color:${MUTED};padding-top:10px;">All of this ran on Facebook and Instagram.</div>`
        : channels.google
          ? `<div style="font-size:12px;color:${MUTED};padding-top:10px;">All of this ran on Google.</div>`
          : ''

  return `<!doctype html><html><body style="margin:0;padding:0;background:#F1F5F9;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F1F5F9;padding:24px 12px;">
<tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#FFFFFF;border-radius:12px;font-family:Arial,Helvetica,sans-serif;">

<tr><td style="padding:26px 28px 6px;">
  <div style="font-size:12px;color:${BRAND};font-weight:700;letter-spacing:.4px;text-transform:uppercase;">Your week in ads</div>
  <div style="font-size:22px;font-weight:700;color:${INK};padding-top:4px;">${esc(first)}</div>
  <div style="font-size:13px;color:${MUTED};padding-top:2px;">${esc(week.label)}</div>
</td></tr>

<tr><td style="padding:14px 28px 0;">
  <div style="font-size:15px;color:${INK};line-height:1.55;">${summary.map(esc).join(' ')}</div>
  ${channelLine}
</td></tr>

<tr><td style="padding:18px 22px 0;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="6" border="0"><tr>
  ${tile('Spend', money(totals.spend), deltaHtml(d.spend, { neutral: true }))}
  ${tile('Leads', fmtLeads(totals.leads), deltaHtml(d.leads))}
  ${tile('Cost per lead', totals.cpl > 0 ? money(totals.cpl) : '&mdash;', totals.cpl > 0 ? deltaHtml(d.cpl, { lowerIsBetter: true }) : '')}
  ${tile('Impressions', fmtInt(totals.impressions), deltaHtml(d.impressions))}
  ${tile('Click rate', `${totals.ctr}%`, deltaHtml(d.ctr))}
  </tr></table>
</td></tr>

${
  topAd
    ? `<tr><td style="padding:16px 28px 0;">
  <div style="padding:10px 14px;background:${SOFT};border-radius:8px;font-size:13px;color:${INK};">
    <strong>Best ad last week:</strong> ${esc(topAd.name)} brought ${fmtLeads(topAd.leads)} ${plural(topAd.leads, 'lead', 'leads')} for ${money(topAd.spend)}.
  </div>
</td></tr>`
    : ''
}

<tr><td style="padding:22px 28px 0;">
  <div style="font-size:15px;font-weight:700;color:${INK};padding-bottom:6px;">The number that matters most</div>
  <div style="font-size:13px;color:${INK};line-height:1.6;">${WHY_RETURN.map((p) => `<p style="margin:0 0 8px;">${esc(p)}</p>`).join('')}
  ${rn.map((p) => `<p style="margin:0 0 8px;padding:10px 12px;background:#FFF7ED;border-left:3px solid ${BRAND};border-radius:4px;">${esc(p)}</p>`).join('')}</div>
  ${
    reportUrl
      ? `<div style="padding-top:6px;"><a href="${esc(reportUrl)}" style="display:inline-block;background:${BRAND};color:#fff;text-decoration:none;font-weight:700;font-size:14px;padding:10px 16px;border-radius:8px;">Tell us how the leads did</a>
      <div style="font-size:11px;color:${MUTED};padding-top:6px;">Takes 20 seconds. Or just reply to this email with a number.</div></div>`
      : `<div style="font-size:13px;color:${INK};">Reply to this email with how many of the leads booked, and roughly what they were worth.</div>`
  }
</td></tr>

<tr><td style="padding:22px 28px 0;">
  <div style="font-size:15px;font-weight:700;color:${INK};padding-bottom:6px;">What each number means</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
  ${GLOSSARY.map(
    (g) =>
      `<tr><td style="padding:6px 0;border-top:1px solid ${LINE};font-size:13px;color:${INK};line-height:1.5;"><strong>${esc(g.label)}.</strong> ${esc(g.text)}</td></tr>`
  ).join('')}
  </table>
</td></tr>

<tr><td style="padding:22px 28px 28px;">
  <div style="border-top:1px solid ${LINE};padding-top:14px;font-size:12px;color:${MUTED};line-height:1.6;">
    These numbers come straight from your ad accounts for ${esc(week.label)}. Reply to this email with any question and a real person answers.
    <div style="padding-top:8px;">${esc(agencyName)}</div>
  </div>
</td></tr>

</table></td></tr></table></body></html>`
}

/** The same report as plain text, for a text message or a Slack paste. */
export function renderWeeklyText(model, { reportUrl = '' } = {}) {
  const { client, week, totals, topAd, summary, returnNote: rn } = model
  const lines = [
    `${client.name}: your week in ads, ${week.label}`,
    '',
    ...summary,
    '',
    `Spend: ${money(totals.spend)}`,
    `Leads: ${fmtLeads(totals.leads)}`,
    `Cost per lead: ${totals.cpl > 0 ? money(totals.cpl) : 'n/a'}`,
    `Impressions: ${fmtInt(totals.impressions)}`,
    `Click rate: ${totals.ctr}%`,
  ]
  if (topAd) lines.push('', `Best ad: ${topAd.name} (${fmtLeads(topAd.leads)} ${plural(topAd.leads, 'lead', 'leads')} for ${money(topAd.spend)})`)
  lines.push('', 'The number that matters most', ...WHY_RETURN, ...rn)
  if (reportUrl) lines.push('', `Tell us how the leads did: ${reportUrl}`)
  return lines.join('\n')
}
